version: "3.9"
services:
  db:
    image: postgres:16
    container_name: frutas_pg
    environment:
      POSTGRES_USER: frutas
      POSTGRES_PASSWORD: frutas
      POSTGRES_DB: frutasdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frutas -d frutasdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
